homebrew_installed_packages:
  - cowsay
  - git
  - terraform
  - docker
  - python
  - spotify
  - zoom
  - awscli
  - iterm

pip_packages:
  - name: aws-adfs

mas_installed_apps:
  - { id: 497799835, name: "Xcode" }

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
