---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  - git
  - terraform
  - docker
  - python
  - spotify
  - zoom
  - awscli
  - iterm
  - visual-studio-code

pip_packages:
  - name: aws-adfs

mas_installed_apps:
  - {id: 497799835, name: "Xcode"}

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files: []
# - .zshrc
# - .gitignore
# - .inputrc
# - .osx
# - .vimrc

homebrew_cask_appdir: /Applications
homebrew_cask_apps: []
# - docker
# - firefox
# - google-chrome

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
